mysql:
  host: localhost
  port: 3306
  user: root
  password: "сайнес гпт кодер"
  database: lite_shame

ban:
  reason: "30d &cОбнаружено сторонние ПО. &7&o(Ошибка? - свяжитесь с разработчиком &f&l@stickshield_ac_bot &7&o) --sender=&c&lАнтиЧит"
  broadcast: "litebans broadcast &7[&x&F&B&0&8&0&8&lАЧ&7]&r &f%player% &fбыл наказан античитом."